### ISSUE TITLE
Issue with produce for unattended krill installation (clone)

### ISSUE THREAD

**Issue by ChrisJackHowe** [pieroproietti/penguins-eggs-legacy#241]
My goal is to create a system that uses krill to run an unattended installation of a cloned system
During the produce command I get this error
## Error
``` 
eggs >>> eggs will SAVE users and users' data UNCRYPTED on the live.
Error: ENOENT: no such file or directory, open '/etc/calamares/settings.conf'
Code: ENOENT
```
I am running the following command after copying my eggs.yaml and my krill.yaml file below into /etc/penguins-eggs.d. This error message does not make a whole lot of sense to me since I do not want to use calamares. So it should not be trying to read calamares files.
``` bash
sudo eggs produce --clone --release --nointeractive
```

I am using ubuntu 22.04 on a virtual box VM (amd64)

## eggs.yaml
```yaml
version: 9.4.16
snapshot_dir: /home/eggs/
snapshot_prefix: companyName- 
snapshot_excludes: /usr/local/share/penguins-eggs/exclude.list
snapshot_basename: edge 
user_opt: live 
user_opt_passwd: '1234' 
root_passwd: '1234' 
theme: eggs 
force_installer: false 
make_efi: true
make_md5sum: false
make_isohybrid: true
compression: zstd -b 256K -Xcompression-level 1
ssh_pass: true
timezone: America/New_York
locales_default: en_US.UTF-8
locales:
  - en_US.UTF-8
pmount_fixed: false
machine_id: 08a081c428c9473f9188c362f742773e
vmlinuz: /boot/vmlinuz-5.19.0-43-generic
initrd_img: /boot/initrd.img-5.19.0-43-generic
```

## Krill.yaml
```yaml
# Penguin's eggs
# krill.yaml
---
# welcome (put your language, example: it_IT.UTF-8)
language: 'en_US.UTF-8'

# location (put your location, example region: "Europe", zone: "Rome")
region: 'America'
zone: 'New_York'

# keyboard (put your values example: keyboardModel: "pc105", keyboardLayout: "it")
keyboardModel: 'pc105'
keyboardLayout: 'us'
keyboardVariant: ''
keyboardOption: ''

# partition (leave it unchanged)
installationDevice: ''
installationMode: 'standard'
filesystemType: 'ext4'
userSwapChoice: 'small'

# users (Here you can put your default user, password, etc)
name: 'operator'
fullname: 'operator'
password: 'operator'
rootPassword: '1234'
autologin: true
hostname: ''

# network (leave it unchanged)
iface: ""
addressType: 'dhcp'
address: ''
netmask: ''
gateway: ''
domain: ''
dns: ''
```
