### ISSUE TITLE
Krill installer fails on actual hardware

### ISSUE THREAD

**Issue by ChrisJackHowe** [pieroproietti/penguins-eggs-legacy#245]
Hello,
I am having problems using the krill installer on a certain machine. This issue occurs when the iso is being installed on actual hardware instead of a vm. The iso in question succeeds in installing on a virtual box machine. Before beginning this project, I tested penguins-eggs on the target machine by creating an iso with a VM and installing the iso on the target machine with calamares.

# Configuration
I am using ubuntu 22.04
## Machine
* Memory: 16GB
* Processor: Intel Core i7-8650U @1.9Ghz x 8
* Graphics: Mesa Intel UHD Graphics 620 ( KBL GT2)
* Disk Capacity: 1Tb
* 64 bit

# Errors I am seeing
The installation is failing at various points of the installer process.
One possible problem I noticed is that krill is displaying `Erase disk /dev/sda` when it should be showing /dev/nvme01
A little more information that may be useful is that when trying to install from an iso created with a vm, the installation process takes almost no time and does not decompress the file system. When installing from an iso created with the target machine, the installation process gets partially through the installation process.

With an iso generated using the same hardware that it will be installed on later I get this error.
`eggs >>> {"errno":-28,"syscall":"write","code":"ENOSPC","name":"ShellJSInternalError"}`
The installation step is `machineid` (progress 46%)

With an iso generated from a vm being applied to the real machine I get these errors
`eggs >>> {"errno":-2,"syscall":"open","code":"ENOENT","path":"/temp/calamares-krill-root/etc/initramfs-tools/conf.d/resume"}.`
The installation step is `Create hostname` (progress 64%)

`eggs >>> {"errno:-2,"syscall":"open","code":"ENOENT","path":"/tmp/calamares-krill-root/etc/default/grub"}/`
The installation step is `bootloader-config` (progress 82%)

# How to recreate this issue
error occurs while running` /usr/bin/eggs install -un` I have also tested `/usr/bin/eggs install` without the flags, along with attempting the installation with and without internet.

## eggs.yaml is generated from this bash
```bash
version: $(eggs version | grep penguin-eggs/ | cut -c15-21)
snapshot_dir: /home/eggs/
snapshot_prefix: $prefix-
snapshot_excludes: /usr/local/share/penguins-eggs/exclude.list
snapshot_basename: $base
user_opt: $live_user  
user_opt_passwd: '$live_user_pass'
root_passwd: '$live_root_pass' 
theme: eggs 
force_installer: false
make_efi: true
make_md5sum: false
make_isohybrid: true
compression: zstd -b 256K -Xcompression-level 1
ssh_pass: true
timezone: America/New_York
locales_default: en_US.UTF-8
locales:
  - en_US.UTF-8
pmount_fixed: false
machine_id: $(cat /var/lib/dbus/machine-id)
vmlinuz: /boot/vmlinuz-$(uname -r)
initrd_img: /boot/initrd.img-$(uname -r)
EOF
```

## krill .yaml
```yaml
# Penguin's eggs
# krill.yaml
---
# welcome (put your language, example: it_IT.UTF-8)
language: 'en_US.UTF-8'

# location (put your location, example region: "Europe", zone: "Rome")
region: 'America'
zone: 'New_York'

# keyboard (put your values example: keyboardModel: "pc105", keyboardLayout: "it")
keyboardModel: 'pc105'
keyboardLayout: 'us'
keyboardVariant: ''
keyboardOption: ''

# partition (leave it unchanged)
installationDevice: ''
installationMode: 'standard'
filesystemType: 'ext4'
userSwapChoice: 'small'

# users (Here you can put your default user, password, etc)
name: 'operator'
fullname: 'operator'
password: 'operator'
rootPassword: '1234'
autologin: true
hostname: ''

# network (leave it unchanged)
iface: ""
addressType: 'dhcp'
address: ''
netmask: ''
gateway: ''
domain: ''
dns: ''
```
