### ISSUE TITLE
/boot/vmlinuz-linux not exists! (arm64)

### ISSUE THREAD

**Issue by abirabedinkhan** [pieroproietti/penguins-eggs-legacy#360]
When I ran this command `saplaos@BongoPC:~/Downloads$ sudo eggs produce --clone` it returned the following ->
```
command: produce --clone

- creating configuration's files...
Due the lacks of calamares package set force_installer = false
/boot/vmlinuz-linux not exists!
```

**Comment by abirabedinkhan** [comment]
contents of boot directory:
```
saplaos@BongoPC:~/Downloads$ ls /boot
armbianEnv.txt                  dtb                  initrd.img-5.15.27-station  vmlinuz-5.15.27-station
armbian_first_run.txt.template  dtb-5.15.27-station  System.map-5.15.27-station
boot.bmp                        extlinux             uInitrd
config-5.15.27-station          Image                uInitrd-5.15.27-station
```

**Comment by pieroproietti** [comment]
Yes @abirabedinkhan,

until now I did ISO images of raspberry, using VMs on [proxmox-ve](https://github.com/jiangcuo/Proxmox-Port) installed on my Raspi 4 8GB.

This let me to have about the same architecture of a PC: CDROM, UEFI BIOS and so on.

Unfortunately, I'm not yet able to do the same with real raspberry - in my case - or on your sistem, but we can try.

This error came from the way `/proc/cmdline` exists on your system... here is a example from my PC amd64 : 

`BOOT_IMAGE=/vmlinuz-6.5.13-5-pve root=/dev/mapper/father--vg-root ro quiet`

This is used [here](https://github.com/pieroproietti/penguins-eggs/blob/fa6198f01e7b0252b648dc3fca2c1bc59e08743c/src/classes/utils.tsx#L121) to get the path of vmlinuz and initrd.img.  

We must to change something to find the right paths for them.

Told that, you can just edit `/etc/penguins-eggs.d/eggs.yaml`, put the right path for vmlinuz and initrd.img and continue.

**Comment by pieroproietti** [comment]
This is `/etc/penguins-eggs.yaml` on my system, just as sample:

``` yaml
compression: fast
force_installer: true
initrd_img: /boot/initrd.img-6.5.13-5-pve
machine_id: 604f58a358594f6a8833daa259a8b663
make_efi: true
make_isohybrid: true
make_md5sum: false
pmount_fixed: false
root_passwd: evolution
snapshot_basename: father
snapshot_dir: /home/eggs/
snapshot_excludes: /etc/penguins-eggs.d/exclude.list
snapshot_mnt: /home/eggs/.mnt/
snapshot_prefix: egg-of_debian-bookworm-
ssh_pass: false
theme: eggs
timezone: Europe/Rome
user_opt: live
user_opt_passwd: evolution
version: 9.7.2
vmlinuz: /boot/vmlinuz-6.5.13-5-pve
```
