### ISSUE TITLE
Problems on Debian 13 "Trixie"

### ISSUE THREAD

**Issue by vaultdweller-2287** [pieroproietti/penguins-eggs-legacy#444]
It's me again! 

I have been having trouble on a Debian system with Penguin's Eggs where when attempting to run get-eggs I get an error stating that "Penguin's eggs is only for DEBIAN/DEVUAN/UBUNTU based systems!".

Up to that point I did change /etc/os-release and /etc/lsb-release to my liking but keeping the necessary parts for repos.

Any ideas on how to fix this would be greatly appreciated.

**Comment by pieroproietti** [comment]
That version you have of Debian, and that version of eggs? From Yesterday I renew all the versione of ISOs, Debian, Devuan Ubuntu and others, and don't get that problem.

On the last version I removed dependency from lsb-release, so now we just check /etc/os-release and, for Debian family, the value of VERSION_CODENAME, so you , must have any valid value here,  example:
`VERSION_CODENAME=bookworm`

or 
`VERSION_CODENAME=trixie`

There is also possibility to change this, and have a custom VERSION_CODENAME, but in this case you must to edit `/usr/lib/penguins-eggs/conf/derivatives.yaml`, in this way:

on `/etc/os-release`

`VERSION_CODENAME=my-customized-version`

Then in `/usr/lib/penguins-eggs/conf/derivatives.yaml`

```
...
- id: bookworm
  distroLike: Debian
  family: debian
  ids:
    - my-customized-version
    - kali-rolling # kali
    - faye    # LMDE 6
    - Sparky  # SparkyLinux 7
    - ara     # Parrot ara
```
